meet_and_play/accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    
]

meet_and_play/game_announcement/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('create', views.create, name='create'),
    path('<int:game_announcement_id>', views.detail, name='detail'),
    path('<int:game_announcement_id>/join', views.join, name='join'),
    path('<int:game_announcement_id>/resign', views.resign, name='resign'),
]

meet_and_play/meet_and_play/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from game_announcement import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('announcements/', include('game_announcement.urls')),
]

meet_and_play/accounts/models.py
from django.db import models

# Create your models here.

meet_and_play/game_announcement/models.py
from django.db import models
from datetime import datetime 
from django.contrib.auth.models import User
from django.conf import settings

SKILL_LEVEL_CHOICES = (
	('0', 'Recreational'),
	('1',  'Amatuer'),
	('2', 'Average'),
	('3',  'Good'),
	('4', 'Very Good'),
)

SPORT_CHOICES = (
	('0', 'Football'),
	('1',  'Basketball'),
	('2', 'Volleyball'),
)

class Game_Announcement(models.Model):
	""" doc to do"""

	sport = models.CharField("Sport", max_length=100, choices=SPORT_CHOICES)
	location = models.CharField("Location", default="Location",max_length=100)
	start_time = models.DateTimeField(default=datetime.now)
	end_time = models.DateTimeField(default=datetime.now)
	wanted_people = models.IntegerField()
	registered_people = models.IntegerField(default=0)
	price = models.FloatField(default=0)
	skill_level = models.CharField("Level of skills", max_length=100, choices=SKILL_LEVEL_CHOICES)
	description = models.TextField("Description")
	pub_date = models.DateTimeField(default=datetime.now)
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	joined = models.CharField(default=";",max_length=10000)

	def joined_users(self):
		joined_list=self.joined.split(';')
		return joined_list[1:-1]

	def did_user_join(self, user_id):
		if str(user_id) in self.joined_users():
			return True 
		return False

meet_and_play/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

def signup(request):
    if request.method == 'POST':
        # User has info and wants an account now!
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error':'Username has already been taken'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], email=request.POST['email'], password=request.POST['password1'])
                auth.login(request,user)
                return redirect('home')
        else:
            return render(request, 'accounts/signup.html', {'error':'Passwords must match'})
    else:
        # User wants to enter info
        return render(request, 'accounts/signup.html')

def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'],password=request.POST['password'])
        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'accounts/login.html',{'error':'username or password is incorrect.'})
    else:
        return render(request, 'accounts/login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('home')

meet_and_play/game_announcement/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from game_announcement.models import Game_Announcement, SPORT_CHOICES, SKILL_LEVEL_CHOICES
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime

def home(request):
    announcements = Game_Announcement.objects.all()
    user_id = str(request.user.id)
    return render(request, 'game_announcement/home.html', {'ann':announcements, 'user_id': user_id })

@login_required(login_url="/accounts/signup")
def create(request):
    if request.method == 'POST':
        if request.POST['sport'] and request.POST['location'] and request.POST['start_date'] and request.POST['end_date'] and request.POST['start_time'] and request.POST['end_time'] and request.POST['wanted_people'] and request.POST['skill_level'] and request.POST['price'] and request.POST['description'] :
            announcement = Game_Announcement()
            announcement.sport = request.POST['sport']
            announcement.location = request.POST['location']
            start_date = request.POST['start_date']
            end_date = request.POST['end_date']
            start_time = request.POST['start_time']
            end_time = request.POST['end_time']

            st_t = str(start_date) +" "+ str(start_time)
            et_t = str(end_date) +" "+ str(end_time)

            announcement.start_time = datetime.strptime(st_t, "%Y-%m-%d %H:%M")
            announcement.end_time = datetime.strptime(et_t, "%Y-%m-%d %H:%M")            

            announcement.wanted_people = request.POST['wanted_people']
            #announcement.registered_people = 0
            announcement.skill_level = request.POST['skill_level']
            announcement.price = request.POST['price']
            announcement.description = request.POST['description']
            announcement.pub_date = timezone.datetime.now()
            announcement.creator = request.user
            announcement.save()
            return redirect('/announcements/' + str(announcement.id))
        else:
            return render(request, 'game_announcement/create.html',{'error':'All fields are required.'})
    else:
        return render(request, 'game_announcement/create.html', {'sport_choices': SPORT_CHOICES, 'skill_choices': SKILL_LEVEL_CHOICES })

def detail(request, game_announcement_id):
    announcement = get_object_or_404(Game_Announcement, pk=game_announcement_id)
    users_ids_list = announcement.joined_users()
    users_list = []
    is_user_signed = announcement.did_user_join(request.user.id)
    for uid in users_ids_list:
        users_list.append(User.objects.get(pk=int(uid)))
    return render(request, 'game_announcement/detail.html',{'announcement':announcement, 'users_list': users_list, 'is_user_signed': is_user_signed})

@login_required(login_url="/accounts/signup")
def join(request, game_announcement_id):
    announcement = get_object_or_404(Game_Announcement, pk=game_announcement_id)
    if announcement.did_user_join(request.user.id):
        announcements = Game_Announcement.objects.all()
        return render(request, 'game_announcement/home.html', {'ann':announcements, 'error':'You\'ve already joined this game'})
    if announcement.registered_people >= announcement.wanted_people:
        announcements = Game_Announcement.objects.all()
        return render(request, 'game_announcement/home.html', {'ann':announcements, 'error':'This game is already full!'})
    announcement.joined += str(request.user.id)
    announcement.joined += ';'
    announcement.registered_people += 1
    announcement.save()
    return redirect('/announcements/' + str(announcement.id))

@login_required(login_url="/accounts/signup")
def resign(request, game_announcement_id):
    announcement = get_object_or_404(Game_Announcement, pk=game_announcement_id)
    users_list = announcement.joined_users()
    users_list.remove(str(request.user.id))
    new_joined_list = ";"
    for u in users_list:
        new_joined_list += str(u.id)
        new_joined_list += ";"
    announcement.joined = new_joined_list
    announcement.registered_people -= 1
    announcement.save()
    return redirect('/announcements/' + str(announcement.id))

meet_and_play/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container col-md-6 pt-3 py-3">
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}
    <form class="form-signin" method="POST" action="{% url 'login' %}">
        <h1 class="h3 my-5 font-weight-normal">Please sign in</h1>

        {% csrf_token %}

        <label for="inputName" class="sr-only">Username</label>
        <input name="username" type="text" id="inputName" class="form-control mb-1" placeholder="Username" required autofocus>

        <label for="inputPassword" class="sr-only">Password</label>
        <input name="password" type="password" id="inputPassword" class="form-control mb-1" placeholder="Password" required>

        <button class="btn btn-lg btn-block mt-5 btn-dark" type="submit">Sign in</button>
    </form>
</div>

{% endblock %}

meet_and_play/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="container col-md-6 pt-3 py-3">
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}
    <form class="form-signin" method="POST" action="{% url 'signup' %}">
        <h1 class="h3 my-5 font-weight-normal">Sign up!</h1>

        {% csrf_token %}

        <label for="inputName">Username</label>
        <input name="username" type="textbox" id="inputName" class="form-control mb-2" placeholder="Username" required autofocus>

        <label for="inputPassword">Password</label>
        <input name="password1" type="password" id="inputPassword" class="form-control mb-2" placeholder="Password" required>

        <label for="inputPassword">Confirm password</label>
        <input name="password2" type="password" id="inputPassword" class="form-control mb-2" placeholder="Password" required>

        <label for="inputEmail">Email</label>
        <input name="email" type="email" id="inputEmail" class="form-control mb-2" placeholder="Username" required autofocus>

        <button class="btn btn-lg btn-block mt-5 btn-dark" type="submit">Sign up</button>
    </form>    
</div>

{% endblock %}

meet_and_play/game_announcement/templates/game_announcement/create.html
{% extends 'base.html' %}

{% block content %}

<div class="container col-md-6 pt-3 py-3">
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}

    <form method="POST" action="{% url 'create' %}" enctype="multipart/form-data">
        <h1 class="h3 my-5 font-weight-normal">Create game</h1>
        {% csrf_token %}

        <div class="form-group">
            <label for="sportSel">Sport</label>
            <select class="custom-select d-block w-100" id="sportSel" name="sport" autofocus>
              {% for value, sport in sport_choices %}
                <option value={{value}}>{{ sport }}</option>
              {% endfor %}
            </select>
        </div>
        
        <label for="inputLocation">Location</label>
        <input name="location" type="textbox" id="inputLocation" class="form-control mb-2" required />

        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="inputSDate">Start date</label>
            <input name="start_date" type="date" id="inputSDate" class="form-control" required/>
          </div>
          <div class="col-md-6 mb-3">
            <label for="inputSTime">Start time</label>
            <input name="start_time" type="time" id="inputSTime" class="form-control mb-2" required/>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="inputEDate">End date</label>
            <input name="end_date" type="date" id="inputEDate" class="form-control" required/>
          </div>
          <div class="col-md-6 mb-3">
            <label for="inputSTime">End time</label>
            <input name="end_time" type="time" id="inputETime" class="form-control mb-2" required/>
          </div>
        </div>

        <label for="inputWPAmount">Wanted amount of people</label>
        <input name="wanted_people" type="number" id="inputWPAmount" min="1" class="form-control mb-2"/>

        <label for="inputPrice">Price</label>
        <input name="price" type="text" id="inputPrice" class="form-control mb-2"/>

        <div class="form-group">
            <label for="skillSel">Skill level</label>
            <select class="custom-select d-block w-100" id="skillSel" name="skill_level">
              {% for value, skill in skill_choices %}
                <option value={{value}}>{{ skill }}</option>
              {% endfor %}
            </select>
          </div>
        
        <label for="inputDesc">Description</label>
        <input name="description" type="textarea" id="inputDesc" class="form-control mb-2"/>

        <input class="btn btn-dark btn-lg btn-block mt-5" type="submit" value="Add announcement" />
    </form>
</div>
{% endblock %}

meet_and_play/game_announcement/templates/game_announcement/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="jumbotron">
  <p class="text-right"><span class="oi oi-map-marker"></span></a><b>  Location: </b> {{announcement.location}}</p>
  <h1 class="display-4">
    <img src="{% static "images/"%}{{ announcement.get_sport_display }}.svg"/>
    {{ announcement.get_sport_display }}
  </h1>
 <hr class="my-4">
<p><b>Description: </b> {{announcement.description}} </p>
  <p><b>Start time: </b> {{announcement.start_time}} </p>
  <p><b>End time: </b> {{announcement.end_time}} </p>
  <p><b>Wanted: </b> {{announcement.wanted_people}} </p>
 <p><b>Registered: </b> {{announcement.registered_people}} </p>
  <p><b>Price: </b> {{announcement.price}} </p>
  <p><b>Skill level: </b> {{announcement.skill_level}} </p>
  <p><b>Publication date: </b> {{announcement.pub_date}} </p>
  <p><b>Creator: </b> {{announcement.creator}} </p>
  <p><b>Creator mail: </b> {{announcement.creator.email}} </p>
  
  {% if is_user_signed %}
  <p class="lead">
  <a href="{% url 'resign' announcement.id %}">
              <button class="btn btn-danger btn-lg btn-block">
                 Resign 
              </button>
            </a>
  </p>
  {% else %}
  <p class="lead">
    <a href="{% url 'join' announcement.id %}">
              <button class="btn btn-dark btn-lg btn-block">
               Join! 
              </button>
    </a>
  </p>
  {% endif %}
</div>

<h3>Registered users:</h3>
<ul class="list-group">
 {% for u in users_list %}
 <li class="list-group-item">{{u}}</li>
{% endfor %}
</ul>

{% endblock %}

meet_and_play/game_announcement/templates/game_announcement/home.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<div class="album pt-3 py-3">
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}

    {% for a in ann %}
    <div class="card mb-3 shadow-sm" onclick="window.location='{% url 'detail' a.id %}';" style="cursor: pointer;">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <img src="{% static "images/"%}{{ a.get_sport_display }}.svg"/>
          </div>
          <div class="col-md-5">
            <p class="card-text">{{ a.location }}</p>
            <p class="card-text">{{ a.start_time }}</p>
          </div>
          <div class="col-md-5">
            <p class="card-text">{{a.registered_people}} / {{a.wanted_people}}</p>
            <p class="card-text text-muted">{{a.get_skill_level_display}}</p>
            {% if user_id in a.joined_users %}
              <a href="{% url 'resign' a.id %}">
              <button class="btn btn-danger btn-lg btn-block">
                Resign 
              </button>
              </a>
            {% else %}
              <a href="{% url 'join' a.id %}">
              <button class="btn btn-dark btn-lg btn-block">
                 Join! 
              </button>
              </a>
            {% endif %}  
            
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

meet_and_play/meet_and_play/templates/base.html
<!doctype html>
<html lang="en">
<head>
  {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Meet&Play</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="{% static 'open-iconic/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet">
</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
      <img src="{% static 'images/logo.svg' %}" height=60 class="d-inline-block alighn-top" alt="Meet&Play"/>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'create' %}">Create <span class="oi oi-plus"></span></a>
          <a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <span class="oi oi-account-logout"></span></a>
          <form id="logout" method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <input type="hidden" />
          </form>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'signup' %}">Create <span class="oi oi-plus"></span></a>
          <a class="nav-item nav-link" href="{% url 'signup' %}">Sign Up <span class="oi oi-person"></span></a>
          <a class="nav-item nav-link" href="{% url 'login' %}">Login <span class="oi oi-account-login"></span></a>
          {% endif %}
        </div>
      </div>
      </div>
    </nav>
  </header>

  <div class="container">

    {% block content %}
    {% endblock %}

  </div>

  <footer class="text-muted">
    <div class="container text-center">
      <p>Have a happy {% now "Y" %}</p>
      </div>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>